### ISSUE TITLE
NoPluginsCommand v1.1-SNAPSHOT does not specify an api-version

### ISSUE THREAD

**Issue by lifeofguenter** [BGHDDevelopment/NoPluginCommand#9]
> [12:00:45 WARN]: Legacy plugin NoPluginsCommand v1.1-SNAPSHOT does not specify an api-version

**Comment by BGHDDevelopment** [comment]
Does it start correctly anyway? This should not be an issue.

**Comment by lifeofguenter** [comment]
It works perfectly, but I thought it might be good to get rid of the warning anyways :)
